### ISSUE TITLE
pip v1.1 error

### ISSUE THREAD

**Issue by mickstevens** [signalwire/signalwire-python-old#1]
Hi Luca, thanks for the pip package update. Still throws an error though, in the attached example I think due to no "signalwire.rest" in /rest/__init__.py ? Still quite a few refs in there to Twilio!? 🤔
![pip signalwire 1 1 rest error](https://user-images.githubusercontent.com/1260281/47087713-9bcecb80-d214-11e8-9f00-b95d98921c4e.png)

**Comment by lpradovera** [comment]
Hello,
this is what I get running on an "empty" machine:
```{17:43}[2.5.0]~/projects/signalwire-python-sdk:master ✗ ➭ docker run -ti prodpy
/app # cp examples/make_call.py /tmp
/app # cd
~ # python /tmp/make_call.py
Traceback (most recent call last):
  File "/tmp/make_call.py", line 10, in <module>
    url="https://cdn.signalwire.com/default-music/playlist.xml"
  File "/usr/local/lib/python3.7/site-packages/twilio/rest/api/v2010/account/call/__init__.py", line 119, in create
    data=data,
  File "/usr/local/lib/python3.7/site-packages/twilio/base/version.py", line 209, in create
    raise self.exception(method, uri, response, 'Unable to create record')
twilio.base.exceptions.TwilioRestException:
HTTP Error Your request was:

POST /Accounts/YOURACCOUNT/Calls.json

Signalwire returned the following information:

Unable to create record

More information may be available here:

https://www.signalwire.com/docs/errors/404


~ # exit
{17:44}[2.5.0]~/projects/signalwire-python-sdk:master ✗ ➭ cat Dockerfile.prod
FROM python:3.7-alpine

COPY . /app
WORKDIR /app

RUN pip install signalwire
CMD ["sh"]

{17:44}[2.5.0]~/projects/signalwire-python-sdk:master ✗ ➭ docker build -f Dockerfile.prod -t prodpy .```

**Comment by lpradovera** [comment]
It is failing but the require works. Feel free to test using the above mini-Dockerfile.

**Comment by mickstevens** [comment]
Hi Luca,

Yes, as you can see from your example, when running make_call.py on the
empty machine the SignalWire Python script calls the Twilio package:

  File "/usr/local/lib/python3.7/site-packages/*twilio*/rest/api/v2010/account/call/__init__.py",
line 119, in create

Not, presumably as you would hope the __init__.py in
/usr/local/lib/python3.7/site-packages/*signalwire ? *

*Rgds, Mick*

*------------------------------------------------------*

**Comment by lpradovera** [comment]
Hello,
thanks for your report. The package currently includes the Twilio library to make it easier for existing Twilio clients to migrate to Signalwire and take advantage of our lower pricing and new features. Eventually, we will help everyone migrate to our next generation APIs. For now, what you are seeing is just an error message, but the API that is being contacted is Signalwire's.

**Comment by mickstevens** [comment]
Still doesn't work, even using Docker:

/app # python3 call.py
Traceback (most recent call last):
  File "call.py", line 6, in <module>
    client = signalwire_client(account, token, signalwire_space_url = 'tornado.signalwire.com')
  File "/app/signalwire/rest/__init__.py", line 59, in __init__
    super(Client, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/twilio/rest/__init__.py", line 47, in __init__
    raise TwilioException("Credentials are required to create a TwilioClient")
twilio.base.exceptions.TwilioException: Credentials are required to create a TwilioClient

**Comment by lpradovera** [comment]
Hello,
I released 1.2. Testing it on the above Dockerfile seems to be working fine. Please let us know!

**Comment by mickstevens** [comment]
Installed 1.2:

Installing collected packages: twilio, signalwire
  Found existing installation: twilio 6.17.0
    Uninstalling twilio-6.17.0:
      Successfully uninstalled twilio-6.17.0
Successfully installed signalwire-1.2 twilio-6.16.4

Seems to remove twilio?

Reinstalling twilio via pip:

signalwire 1.2 has requirement twilio==6.16.4, but you'll have twilio 6.19.1 which is incompatible.

The statement that this is independent of twilio is looking a bit suspect?

**Comment by lpradovera** [comment]
Hello,
we pinned Twilio to that specific version.

**Comment by mickstevens** [comment]
Oh, yeh, right! 🤣😉 Well the good news is now working, without Docker, closing.
