### ISSUE TITLE
SDK have errors, ImportError: No module named parse

### ISSUE THREAD

**Issue by ShashiKumar-SignalWire** [signalwire/signalwire-python-old#7]
below error, I am getting when creating Client Object 

Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from signalwire.rest import Client as signalwire_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/signalwire/rest/__init__.py", line 4, in <module>
    from urllib.parse import urlparse, ParseResult
ImportError: No module named parse

**Comment by lpradovera** [comment]
Fixed by #9 . We still recommend using Python 3.
